---
title: "About this site"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I’m an associate professor in Psychology (with an affiliation in Biology) at New York University Abu Dhabi (NYUAD), where I direct the Language, Mind and Brain Lab (LaMB Lab). My work focuses on different aspects of language processing, such as how we perceive speech, how we retrieve words when hearing speech or reading, and how we parse and understand sentences. I am particularly interested in how the language system communicates with our perceptual and memory systems, and I use neuroimaging methods extensively in my research. I am also very fond of pursuing theoretically motivated cross-linguistic work.

If you are interested in research opportunities in my lab, see here.

During the academic year 2019-2020 year, I will be on sabbatical.

Courses that I have taught in the past at NYUAD and may teach again at some point in the future:

PSYCH-UH 1001: Introduction to Psychology
PSYCH-UH 2212: Psychology of Language
PSYCH-UH 2410: Cognition
PSYCH-UH 3615EQ: Lab in Psychology of Language
CDAD-UH 1007EQ: The Mind