---
title: "Research & Output"
---

## Papers

:::::: biblio ::::::

* [Sprouse, J. and [Almeida, D.]{.pub-me}]{.pub-author} (in press). [Electrophysiological methods]{.pub-title}. In: Jon Sprouse (Ed.) [The Oxford Handbook of Experimental Syntax]{.pub-journal}. Oxford University Press.

* [Tucker, M., Idrissi, A., & [Almeida, D]{.pub-me}]{.pub-author}. (2021). [Attraction effects for verbal gender and number are similar but not identical: Self-paced reading evidence from Modern Standard Arabic.</span> <span class="pub-journal">Frontiers in Psychology]{.pub-title}, [11]{.pub-vol}, [3774]{.pub-pages}. https://doi.org/10.3389/fpsyg.2020.586464
    * <i class="fa fa-file-pdf"></i> [OA paper](https://www.frontiersin.org/articles/10.3389/fpsyg.2020.586464/pdf) <i class="ai ai-open-access"></i>
    * <i class="ai ai-figshare"></i> [data & code](https://figshare.com/projects/Attraction_Effects_for_Verbal_Gender_and_Number_Are_Similar_but_Not_Identical_Self-Paced_Reading_Evidence_from_Modern_Standard_Arabic/18823)
    * <i class="fa fa-github"></i> [research compendium](https://github.com/diogo-almeida/TuckerIdrissiAlmeida2021)

* [Tucker, M., Idrissi, A., Sprouse, J., & [Almeida, D]{.pub-me}]{.pub-author}. (2019). [Resumption ameliorates different islands differentially: Acceptability data from Modern Standard Arabic.]{.pub-title} In: Amel Khalfaoui & Matthew Tucker (Eds.). [Proceedings of Perspectives on Arabic Linguistics 30]{.pub-journal} ([159 – 194]{.pub-pages}). John Benjamins. https://doi.org/10.1075/sal.7.09tuc
    * <i class="fa fa-file-pdf"></i> [preprint](https://www.diogoalmeida.net/papers/tucker_idrissi_almeida_2019.pdf)

* [Sprouse, Jon, & [Almeida, D]{.pub-me}]{.pub-author}. (2017). [Setting the empirical record straight: Acceptability judgments appear to be reliable, robust, and replicable.]{.pub-title} [Behavioral and Brain Sciences]{.pub-journal}, [40]{.pub-vol}, [43 – 44]{.pub-pages}. https://doi.org/10.1017/S0140525X17000590
    * <i class="fa fa-file-pdf"></i> [preprint](https://www.researchgate.net/profile/Diogo_Almeida7/publication/316408211_Setting_the_empirical_record_straight_Acceptability_judgments_appear_to_be_reliable_robust_and_replicable/links/5a07ec060f7e9b68229b4ba5/Setting-the-empirical-record-straight-Acceptability-judgments-appear-to-be-reliable-robust-and-replicable.pdf?_sg%5B0%5D=DJZmqG_tQo9_3B8xelozgtlA3PGNVnENd1w2MKW_rXiW7w12CqvZKI1f7pGRZ7mwzcL372LMStEMUinHOI5skQ.TiEvnpIoRhOkyKEiv5JOxn9PBamhfkYwrDL8A9ifs_naeRdfT1zYiwVN4ljKDRensVwZAHuFia93puTcnnkUtw&_sg%5B1%5D=8DAEeSUUKEspPHDfyDbj7vXrJydXpX-4NzKhrPGsTaTcmh8nKmpe3M9h1QLVLUY1hpu6G095fWF6RMRsY0rPXw_LT-hEOXGpE1TjHlur_XLA.TiEvnpIoRhOkyKEiv5JOxn9PBamhfkYwrDL8A9ifs_naeRdfT1zYiwVN4ljKDRensVwZAHuFia93puTcnnkUtw)

* [Schluter, K., Politzer-Ahles, S., Al Kaabi, M., & [Almeida, D]{.pub-me}]{.pub-author}. (2017). [Laryngeal features are phonetically abstract: Mismatch Negativity evidence from Arabic, English, and Russian.]{.pub-title} [Frontiers in Psychology]{.pub-journal}, [8]{.pub-vol}, [746]{.pub-pages}. https://doi.org/10.3389/fpsyg.2017.00746
    * <i class="fa fa-file-pdf"></i> [OA paper](https://www.frontiersin.org/article/10.3389/fpsyg.2017.00746/pdf)  <i class="ai ai-open-access"></i>

* [Politzer-Ahles, S., Xiang, M., & [Almeida, D]{.pub-me}]{.pub-author}. (2017). [“Before” and "after": investigating the relationship between temporal connectives and chronological ordering using [erp]{.sc}s.]{.pub-title} [PLoS ONE]{.pub-journal} [12]{.pub-vol}([4]{.pub-issue}), [e0175199]{.pub-pages}. https://doi.org/10.1371/journal.pone.0175199
    * <i class="fa fa-file-pdf"></i> [OA paper](http://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0175199&type=printable) <i class="ai ai-open-access"></i>

* [Sprouse, J., & [Almeida, D]{.pub-me}]{.pub-author}. (2017). [Design sensitivity and statistical power in acceptability judgment experiments.]{.pub-title} [Glossa]{.pub-journal}, [2]{.pub-vol}([1]{.pub-issue}), [14]{.pub-pages}. https://doi.org/10.5334/gjgl.236
    * <i class="fa fa-file-pdf"></i> [OA paper](https://www.glossa-journal.org/article/4876/galley/12326/download/) <i class="ai ai-open-access"></i>
    * <i class="fa fa-file-excel"></i> [materials](https://www.jonsprouse.com/data/Glossa2017/SA2017.materials.xlsx)
    * <i class="fa fa-chart-column"></i> [data](https://www.jonsprouse.com/data/Glossa2017/SA2017.data.zip)

* [[Almeida, D.]{.pub-me}, & Tucker, M]{.pub-author}. (2017). [The complex structure of errors and the independent visibility of phi-features: Evidence from agreement attraction in Arabic.]{.pub-title} In: Andrew Lamont & Katerina Tetzloff (Eds.) [Proceedings of the 47th Meeting of the North East Linguistics Society, Vol. 1]{.pub-journal} ([45 – 54]{.pub-pages}). Amherst, MA: GLSA.
    * <i class="fa fa-file-pdf"></i> [preprint](https://www.researchgate.net/profile/Diogo_Almeida7/publication/317274975_The_complex_structure_of_agreement_errors_Evidence_from_distributional_analyses_of_Agreement_Attraction_in_Arabic/links/592f730e0f7e9beee7618cce/The-complex-structure-of-agreement-errors-Evidence-from-distributional-analyses-of-Agreement-Attraction-in-Arabic.pdf?_iepl%5BhomeFeedViewId%5D=J8BMstCio7AnG6eA8m1EOFTjqJdTl507H8oJ&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=3pP4vniEN-e554UGWH1lOn9rptHJhQk2lRj3-x5hCtt8_iVT1qgZwH5TQR5Pn7szbBLaAXB9e9pYVyvI-j_vL-V_qYfyqQycLU4hA_FvrZSJ0wttpR1GIt3F.BF2bewA84qhsW2mjmzUzR0_lB3gC8052idJY0GBQ7WYRC2XLA_BikuEn5nHBzQyEufrxubiaiJJcktH9tEhQNkhPgUCh5b5DjvbD0g.UixZwm1os3WJw0Yj-_yQjMH-N2CliqsooLMpxlO7lDkiO93jEJ5FmIzB3O9hrbU0pkqGLXhGwGLxIkEFUpghUGUsTiASl8X89dTwAg.rILPoqlB3pnelRIjLwaZp7pm1GhGn1QNt1SLNmLptuGBextMhRkfcfk5tz8uK24VE5l2B0dKGfrs93afdw6TmBzfSXBmQ6W5ksyYIA)

* [Politzer-Ahles, S., Schluter, K., Wu, K., & [Almeida, D]{.pub-me}]{.pub-author}. (2016). [Asymmetries in the perception of Mandarin tones: Evidence from mismatch negativity.]{.pub-title} [Journal of Experimental Psychology: Human Perception and Performance]{.pub-journal}, [42]{.pub-vol}([10]{.pub-issue}), [1547 – 1570]{.pub-pages}. https://doi.org/10.1037/xhp0000242
    * <i class="fa fa-file-pdf"></i> [OA paper](https://psycnet.apa.org/fulltext/2016-24934-001.pdf) <i class="ai ai-open-access"></i>

* [Schluter, K., Politzer-Ahles, S., & [Almeida, D]{.pub-me}]{.pub-author}. (2016). [No place for /h/. An <span class="sc">erp</span> investigation of English fricative place features.]{.pub-title} [Language, Cognition and Neuroscience]{.pub-hournal}, [31]{.pub-vol}([6]{.pub-issue}), [728 – 740]{.pub-pages}. https://doi.org/10.1080/23273798.2016.1151058
    * <i class="fa fa-file-pdf"></i> [OA paper](https://www.tandfonline.com/doi/pdf/10.1080/23273798.2016.1151058?needAccess=true) <i class="ai ai-open-access"></i>

* [[Almeida, D.]{.pub-me}, Corina, D. & Poeppel, D]{.pub-author}. (2016). [The Processing of biologically plausible and implausible forms in American Sign Language: Evidence for perceptual tuning.]{.pub-title} [Language, Cognition and Neuroscience]{.pub-journal} [31]{.pub-vol}([3]{.pub-issue}), [361 – 374]{.pub-pages}. https://doi.org/10.1080/23273798.2015.1100315
    * <i class="fa fa-file-pdf"></i> [OA paper](https://www.tandfonline.com/doi/pdf/10.1080/23273798.2015.1100315?needAccess=true) <i class="ai ai-open-access"></i>

* [Rogalsky, C., [Almeida, D.]{.pub-me}, Sprouse, J. & Hickok, G]{.pub-author}. (2015). [Sentence processing selectivity in Broca’s area: Evident for structure but not syntactic movement.]{.pub-title} [Language, Cognition and Neuroscience]{.pub-journal}, [30]{.pub-vol}([10]{.pub-issue}), [1326 – 1338]{.pub-pages}. https://doi.org/10.1080/23273798.2015.1066831
    * <i class="fa fa-file-pdf"></i> [paper](https://www.researchgate.net/profile/Diogo_Almeida7/publication/281107689_Sentence_processing_selectivity_in_Broca%27s_area_evident_for_structure_but_not_syntactic_movement/links/55d5cd9f08aec156b9a53fa5/Sentence-processing-selectivity-in-Brocas-area-evident-for-structure-but-not-syntactic-movement.pdf?_sg%5B0%5D=BGloN6HieTIjTXU-H-CYV3obgP3n-YwHfy_O3Zj9BSB2ix_JCJ6-4-3QV4bOkEklRa9t6Xwa7YV3exC8fu6zzQ.8YKXGun8HsogPWrQlYtIZm067W4YqucwMjq0BrhUidllZUstPJGYUq5FnWAgLKsGxyQ06tYcUoogyRZjwgacBQ&_sg%5B1%5D=ixvS3BaP5lifZPhXP_ZeAZrONWvI2rg216dQfR7HE2qtP6RuJjy-FBGSSSq-NWUs-MvkZGYFiHVt2oi71qeidCVsif1PT_DXK1orYFNYismx.8YKXGun8HsogPWrQlYtIZm067W4YqucwMjq0BrhUidllZUstPJGYUq5FnWAgLKsGxyQ06tYcUoogyRZjwgacBQ&_iepl=)

* [Tucker, M., Idrissi, A., & [Almeida, D]{.pub-me}]{.pub-author}. (2015). [Representing number in the real–time processing of agreement: Self–paced reading evidence from Arabic.]{.pub-title} [Frontiers in Psychology – Language Sciences]{.pub-journal}, [6]{.pub-vol}:[347]{.pub-pages}. https://doi.org/10.3389/fpsyg.2015.00347
    * <i class="fa fa-file-pdf"></i> [OA paper](http://journal.frontiersin.org/article/10.3389/fpsyg.2015.00347/pdf) <i class="ai ai-open-access"></i>
    * <i class="ai ai-figshare"></i> [data & code](https://figshare.com/articles/dataset/_Representing_number_in_the_real-time_processing_of_agreement_Self-paced_reading_evidence_from_Arabic_Compressed_data_in_RData_format_for_direct_download_/4584331)

* [Politzer-Ahles, S., Schluter, K., Wu, K., & [Almeida, D]{.pub-me}]{.pub-author}. (2015). [Asymmetries in the perception of Mandarin tones: Evidence from mismatch negativity.]{.pub-title} In The Scottish Consortium for ICPhS 2015 (Ed.), [Proceedings of the 18th International Congress of Phonetic Sciences]{.pub-journal}. Glasgow, UK: University of Glasgow.
    * <i class="fa fa-file-pdf"></i> [OA paper](https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2015/Papers/ICPHS0380.pdf) <i class="ai ai-open-access"></i>

* [[Almeida, D]{.pub-me}]{.pub-author}. (2014). [Subliminal WH-islands in Brazilian Portuguese and the consequences for syntactic theory.]{.pub-title} [Revista da ABRALIN]{.pub-journal}, [13]{.pub-vol}([2]{.pub-issue}), [55 – 93]{.pub-pages}.
    * <i class="fa fa-file-pdf"></i> [OA paper](http://revista.abralin.org/index.php/abralin/article/view/1187/1110) <i class="ai ai-open-access"></i>
    * <i class="fa fa-file-pdf"></i> [preprint](http://ling.auf.net/lingbuzz/002240/)
    * <i class="ai ai-figshare"></i> [data & code](https://figshare.com/articles/Data_Analysis_scripts_and_materials_for_Almeida_D_2014_Subliminal_wh-islands_in_Brazilian_Portuguese_and_the_consequences_for_syntactic_theory_Revista_da_ABRALIN_13_2_55-91_/7586675)

* [[Almeida, D.]{.pub-me}, & Poeppel, D]{.pub-author}. (2013). [Word–specific repetition effects revealed by [meg]{.sc} and the implications for lexical access.]{.pub-title} [Brain and Language]{.pub-journal}, [127]{.pub-vol}([3]{.pub-issue}), [497 – 509]{.pub-pages}. https://doi.org/10.1016/j.bandl.2013.09.013
    * <i class="fa fa-file-pdf"></i> [paper](https://drive.google.com/open?id=0B36GYIWWvWmTTmhPeWNBOFkwNmc)

* [Sprouse, J., Schütze, C., [Almeida, D]{.pub-me}]{.pub-author}. (2013). [A comparison of informal and formal acceptability judgments using a random sample from Linguistic Inquiry 2001 - 2010.]{.pub-title} [Lingua]{.pub-journal}, [134]{.pub-vol}, [219 – 248]{.pub-pages}. https://doi.org/10.1016/j.lingua.2013.07.002
    * <i class="fa fa-file-pdf"></i> [paper](https://drive.google.com/open?id=0B36GYIWWvWmTd2sxUkZwWGpNRkk)
    * <i class="fa fa-file-pdf"></i> [preprint](http://ling.auf.net/lingbuzz/001352)
    * <i class="fa fa-file-excel"></i> [materials](https://www.jonsprouse.com/data/Lingua2013/SSA.Materials.xlsx)
    * <i class="fa fa-chart-column"></i> [data](https://www.jonsprouse.com/data/Lingua2013/SSA.data.zip)

* [Sprouse, J., & [Almeida, D]{.pub-me}]{.pub-author}. (2013). [The empirical status of data collection methods in syntax: a reply to Gibson and Fedorenko.]{.pub-title} [Language and Cognitive Processes]{.pub-journal}, [28]{.pub-vol}([3]{.pub-issue}), [222 – 228]{.pub-pages}. https://doi.org/10.1080/01690965.2012.703782
    * <i class="fa fa-file-pdf"></i> [paper](https://drive.google.com/open?id=0B36GYIWWvWmTWDR5dTI4MnN5bkE)

* [Sprouse, J., & [Almeida, D]{.pub-me}]{.pub-author}. (2013). [The role of experimental syntax in an integrated cognitive science of language.]{.pub-title} In K. Grohmann & C. Boeckx (Eds.), [The Cambridge Handbook of Biolinguistics]{.pub-journal}. Cambridge University Press.
    * <i class="fa fa-file-pdf"></i> [preprint](https://drive.google.com/open?id=0B36GYIWWvWmTclc3TEFtRjJCcDQ)

* [Sprouse, J., & [Almeida, D]{.pub-me}]{.pub-author}. (2012). [Assessing the reliability of textbook data in syntax: Adger’s Core Syntax.]{.pub-title} [Journal of Linguistics]{.pub-journal}, [48]{.pub-vol}([3]{.pub-issue}), [609 – 652]{.pub-pages}. https://doi.org/10.1017/S0022226712000011
    * <i class="fa fa-file-pdf"></i> [paper](https://drive.google.com/open?id=0B36GYIWWvWmTUHZXdjBpU1EtOW8)
    * <i class="fa fa-file-excel"></i> [materials](https://www.jonsprouse.com/data/JoL2012/SA2012.materials.zip)
    * <i class="fa fa-chart-column"></i> [data](https://www.jonsprouse.com/data/JoL2012/SA2012.materials.zip)

* [Lau, E., [Almeida, D.]{.pub-me}, Hines, P. & Poeppel, D]{.pub-author}. (2009). [A lexical basis for N400 context effects: Evidence from [meg]{.sc}]{.pub-title}. [Brain and Language]{.pub-journal}, [111]{.pub-vol}([3]{.pub-issue}), [161 – 172]{.pub-pages}. https://doi.org/10.1016/j.bandl.2009.08.007
    * <i class="fa fa-file-pdf"></i> [paper](https://drive.google.com/open?id=0B36GYIWWvWmTSHFUM3FNQ3lUNkU)

* [[Almeida, D.]{.pub-me} & Yoshida, Y]{.pub-author}. (2007). [A problem for the Preposition Stranding Generalization.]{.pub-title} [Linguistic Inquiry]{.pub-journal}, [38]{.pub-vol}([2]{.pub-issue}), [349 – 362]{.pub-pages}. https://doi.org/10.1162/ling.2007.38.2.349
    * <i class="fa fa-file-pdf"></i> [paper](https://drive.google.com/open?id=0B36GYIWWvWmTVVpPR1NKbXE3NGs)

* [Corrêa, L. M. S., [Almeida, D.]{.pub-me}, & Porto, R]{.pub-author}. (2004). [On the representation of Portuguese gender–inflected words in the mental lexicon.]{.pub-title} [Brain and Language]{.pub-journal}, [90]{.pub-vol}([1]{.pub-issue}), [63 – 73]{.pub-pages}. https://doi.org/10.1016/S0093-934X%2803%2900420-6
    * <i class="fa fa-file-pdf"></i> [paper](https://drive.google.com/open?id=0B36GYIWWvWmTMm51eWx4RU9vVUk)

::::::::::::::::::::

